all: bin/main

bin/main : obj/main.o lib/libformas.a
	g++ -o bin/main obj/main.o -Llib/ -lformas

lib/libformas.a: obj/punto.o obj/circulo.o
	ar rsv lib/libformas.a obj/punto.o obj/circulo.o

obj/punto.o: src/PUNTO.cpp include/punto.h
	g++ -c src/PUNTO.cpp -o obj/punto.o -Iinclude/

obj/circulo.o: src/CIRCULO.cpp include/punto.h include/circulo.h
	g++ -c src/CIRCULO.cpp -o obj/circulo.o -Iinclude/

obj/main.o: src/main.cpp include/punto.h include/circulo.h
	g++ -c src/main.cpp -o obj/main.o -Iinclude/

clean:
	echo "cleaning..."
	rm obj/*.o lib/*.a bin/*
